docs: add EventManager examples
decentraland/kernel-legacy pull request #106
Opened 2019-04-08 14:08 UTC by menduz

2019-04-09 13:50 UTC, fmiras requested changes
LGTM but I'd to discuss the comments I left

2019-04-09 13:50 UTC, fmiras commented on packages/decentraland-ecs/src/decentraland/Implementation.ts
> +          const data = event.data as any
Wouldn't be cooler to make
```ts
const { data }: any = event
```
so we cast `event.data` object to `any` type once?

2019-04-09 13:50 UTC, fmiras commented on test/unit/ecs.test.tsx
> +    }
Just a comment, this function could be lot more readable if separate them in lambda functions like this:

```ts
function getMaterials(context: SharedSceneContext): DisposableComponent[] {
	return Array.from(context.disposableComponents)
    	.map(pair => pair[1]) // or .map(([, component]) => component)
        .filter(component => component instanceof PBRMaterial)
}
```

or even just asking for the entries:
```ts
function getMaterials(context: SharedSceneContext): DisposableComponent[] {
	return Array.from(context.disposableComponents.entries())
        .filter(component => component instanceof PBRMaterial)
}

```

2019-04-09 13:50 UTC, fmiras commented on packages/decentraland-ecs/src/ecs/EventManager.ts
> +    // tslint:disable-next-line:semicolon
Not related to the PR but what do you think of removing this rule? prettier already remove unnecessary semi-colons for us and we already have 16 matching results of this comment. Is not bad to use it

2019-04-09 14:24 UTC, menduz commented on packages/decentraland-ecs/src/decentraland/Implementation.ts
> +          const data = event.data as any
That does not produce the same result

2019-04-09 15:36 UTC, menduz commented on packages/decentraland-ecs/src/ecs/EventManager.ts
> +    // tslint:disable-next-line:semicolon
Sure, we should wait to merge the open things before, the merge conflicts will kill us

2019-04-09 15:37 UTC, menduz commented on test/unit/ecs.test.tsx
> +    }
Is it that bad? I like functional thing when they save us dozens of lines, without sacrificing readability. This one is pretty clear

2019-04-10 16:42 UTC, merged

2019-04-23 11:33 UTC, nearnshaw commented
@menduz  

I'm documenting events right now.
Will we keep the second argument of the `addListener` function?  I think I remember a conversation we had where you said that was pointless and you'd try to remove it.

```
events.addListener(UpdateEvent, null, ({ entity, dt }) => {
    // function
})
```

Will it remain there for the release?

2019-04-23 15:29 UTC, menduz commented
Yes, it will remain for performance reasons.