feat: make preview work with unity engine
decentraland/kernel-legacy pull request #110
Opened 2019-04-10 14:38 UTC by fmiras

Johny la gente esta muy loca 🎉

2019-04-10 16:19 UTC, menduz requested changes

2019-04-10 16:19 UTC, menduz commented on static/preview.html
> +  <script src="@/unity/Build/UnityLoader.js"></script>
Please start the URL with / to make it relative to the document.origin

2019-04-10 16:19 UTC, menduz commented on packages/unity-interface/dcl.ts
> +  if (!PREVIEW) {
We should always initialize the UI

2019-04-10 16:19 UTC, menduz commented on packages/unity-interface/dcl.ts
> +    }
can we move this id inside loadPreviewScene?

2019-04-10 16:19 UTC, menduz commented on packages/unity-interface/dcl.ts
>      }
can we move this to the `preview.ts` entry point? I feel this has nothing to do with unity

2019-04-10 16:59 UTC, fmiras commented on packages/unity-interface/dcl.ts
> +    }
I didn't get you, what do you mean?

2019-04-10 17:07 UTC, menduz commented on packages/unity-interface/dcl.ts
> +    }
sorry, I meant this `if`

2019-04-11 16:47 UTC, menduz approved these changes

2019-04-11 16:47 UTC, merged