feat: add segment support
decentraland/kernel-legacy pull request #146
Opened 2019-05-02 15:05 UTC by fmiras

Contributes #98 

Can't identify users until identity integration/definitions

2019-05-09 10:12 UTC, eordano approved these changes

2019-05-09 16:09 UTC, menduz requested changes

2019-05-09 16:09 UTC, menduz commented on packages/shared/comms/peers.ts
> +  queueTrackingEvent('User visibility', { uuid, visible })
Following the `Single responsibility principle` it would be better to have a file called `analytics` or something like that, listening to `avatarMessageObservable`.

It will decouple this file from analytics completely

2019-05-09 16:12 UTC, menduz requested changes

2019-05-09 16:12 UTC, menduz commented on packages/shared/world/positionThings.ts
> +      queueTrackingEvent('User Position', { position: cameraVector, distance: distanceTraveled })
Here too, we have a position observable. You can decouple the tracking code from the implementation by listening to the position observable and keep this implementation clean and decoupled from tracking

2019-05-15 14:12 UTC, menduz requested changes

2019-05-15 14:12 UTC, menduz commented on packages/ui/avatar/chatWindow.ts
> +import { queueTrackingEvent } from 'shared/analytics'
this doesn't work since packages/ui is a web worker

2019-05-15 14:12 UTC, menduz commented on packages/shared/analytics.ts
> +avatarMessageObservable.add(({ type, ...data }) => queueTrackingEvent(type, data))
I'd wrap this `observables.add` into functions like `function hookAnalytics() {` and then only call them inside the function `initialize` to avoid side effects at startup

2019-05-16 11:23 UTC, fmiras commented on packages/ui/avatar/chatWindow.ts
> +import { queueTrackingEvent } from 'shared/analytics'
I just removed it, created an issue #180 to make it in another PR

2019-05-16 11:23 UTC, merged