chore: only build modified ECS projects
decentraland/kernel-legacy pull request #167
Opened 2019-05-11 11:25 UTC by fmiras

Contributes to #148 

# What? 
ECS Projects only are going to build in case of modification (even at first `make build`)

**TODO:** 
- [ ] Calculate stat of child folder files

2019-05-13 19:04 UTC, menduz commented on scripts/buildECSprojects.ts
> +;(async () => {
it is better to do 
```ts

2019-05-14 16:08 UTC, eordano commented
why is this blocked?

2019-05-14 16:09 UTC, eordano approved these changes

2019-05-15 15:03 UTC, fmiras commented
> why is this blocked?

It was blocked because we're only stating the parents folder, that means if we change something in `game.ts` it wasn't going to compile eiter. Now that's solved

2019-05-15 15:21 UTC, menduz requested changes
It breaks the watch mode `node ./scripts/buildECSprojects.js --watch`

2019-05-27 19:30 UTC, eordano commented
Is this still blocked? What's the cause of it breaking the watcher?

2019-05-29 08:48 UTC, fmiras commented
> Is this still blocked? What's the cause of it breaking the watcher?
Because in case it doesn't have to rebuild it, it just skip `decentraland-compiler` which is the one in charge of watching those files in the first place

I'll close this PR. We should either implement this logic in `decentraland-compiler` as a `--cache` flag or implement TS 3.4 incremental builds

2019-05-29 08:48 UTC, closed without merging