WIP messages between parcels
decentraland/kernel-legacy pull request #197
Opened 2019-05-24 22:38 UTC by menduz

# What? 
...

# Why? 
...

2019-05-27 19:31 UTC, eordano commented on packages/decentraland-ecs/types/dcl/index.d.ts
> +
@menduz should this file be commited? It looks auto-generated to me

2019-05-31 17:40 UTC, hugoArregui approved these changes

2019-05-31 17:40 UTC, hugoArregui commented on packages/shared/comms/BrokerConnection.ts
> +            this.logger.log('1')
remove this? (maybe I left it here)

2019-06-07 12:02 UTC, eordano reviewed
All nits, I still haven't reviewed the meaty part.

2019-06-07 12:02 UTC, eordano commented on Makefile
> -	cd $(PWD)/packages/decentraland-ecs; $(PWD)/node_modules/.bin/api-extractor run --typescript-compiler-folder "$(PWD)/node_modules/typescript" --local
consider dropping `--verbose`?

2019-06-07 12:02 UTC, eordano commented on Makefile
> +	$(MAKE) build-hell-map
Why are we making a distinction on this set of scenes? I think the granularity is kind of broken/I'd use a different name than "hell map" (`perf-test-scenes`?)

2019-06-07 12:02 UTC, eordano commented on Makefile
> +watch: export NODE_ENV=development
oops?

2019-06-07 12:02 UTC, eordano commented on packages/config/index.ts
> +export const DEBUG_LOCAL_COMMS = location.search.indexOf('LOCAL_COMMS') !== -1 || PREVIEW
How do you feel about `s/DEBUG_LOCAL_COMMS/USE_LOCAL_COMMS`?

2019-06-07 12:02 UTC, eordano commented on packages/decentraland-ecs/api-extractor.json
> +/**
Verbose as F*. 

*No generated code shall be commited to repos*

2019-06-07 12:02 UTC, eordano commented on packages/decentraland-ecs/src/decentraland/Types.ts
> +/** @public */
@menduz what's up with all these jsdocs?

2019-06-07 12:02 UTC, eordano commented on packages/decentraland-ecs/types/@decentraland/CommunicationsController/index.d.ts
> +declare module '@decentraland/CommunicationsController' {
should this file be .gitignored?

2019-06-07 12:02 UTC, eordano commented on packages/decentraland-ecs/types/env/es5.d.ts
>  /// ECMAScript APIs
Should this file be `.gitignored`?

2019-06-07 12:02 UTC, eordano commented on packages/decentraland-ecs/types/tsconfig.json
> -      "@decentraland/EntityController",
Oops?

2019-06-07 12:02 UTC, eordano commented on packages/shared/apis/CommunicationsController.ts
> +}
Beautifully short and effective

2019-06-07 13:53 UTC, fmiras commented on Makefile
> +initialize-ecs-npm-link: build-sdk
This is awesome

2019-06-07 13:55 UTC, fmiras commented on packages/config/index.ts
> +        ? 'https://schema-api-v2.now.sh/dar'
Can we track with either an issue or a TODO task to setup .zone environment for this?

2019-06-07 14:01 UTC, eordano requested changes

2019-06-07 14:01 UTC, eordano commented on packages/shared/comms/BrokerConnection.ts
> +      this.logger.log(state)
.debug?

2019-06-07 14:01 UTC, eordano commented on packages/shared/comms/BrokerConnection.ts
> +  get hasUnreliable() {
`s/hasUnreliableChannel`

2019-06-07 14:01 UTC, eordano commented on packages/shared/comms/BrokerConnection.ts
> +  get hasReliable() {
`s/hasReliableChannel`

2019-06-07 14:01 UTC, eordano commented on packages/shared/comms/BrokerConnection.ts
> +      this.ws.onclose = null
:/ really? shouldn't we call it first?

2019-06-07 14:01 UTC, eordano commented on packages/shared/comms/BrokerConnection.ts
> +        if (this.stats) {
This should be outside of the switch

2019-06-07 14:01 UTC, eordano commented on packages/shared/comms/BrokerConnection.ts
> +      this.logger.log(`signaling state: ${this.webRtcConn!.signalingState}`)
.debug?

2019-06-07 14:01 UTC, eordano commented on packages/shared/comms/CliBrokerConnection.ts
> +      this.logger.log(state)
.debug?

2019-06-07 14:01 UTC, eordano commented on packages/shared/comms/CliBrokerConnection.ts
> +      this.ws.onclose = null
Warning: we should call this first

2019-06-07 14:01 UTC, eordano commented on packages/shared/comms/debug.ts
> +      connection.connection.logDebug()
What does this do?

2019-06-07 14:01 UTC, eordano commented on packages/shared/comms/IBrokerConnection.ts
> +  logDebug(): void
Is `logStateInfo()` a more descriptive name?

2019-06-07 14:01 UTC, eordano commented on packages/shared/comms/index.ts
> +        if (!rawTopics.includes(hash)) {
Thank you <3

2019-06-07 14:01 UTC, eordano commented on public/test-parcels/-100.100.gamekit-cube/game.ts
> +log('hello a a s')
🙁

2019-06-07 14:17 UTC, menduz commented on Makefile
> -	cd $(PWD)/packages/decentraland-ecs; $(PWD)/node_modules/.bin/api-extractor run --typescript-compiler-folder "$(PWD)/node_modules/typescript" --local
It is on purpose, it behaves like an --info tho. It really helped while debugging, so I kept it

2019-06-07 14:18 UTC, menduz commented on Makefile
> +	$(MAKE) build-hell-map
Can we tackle that renaming issue in a different PR?

2019-06-07 14:18 UTC, menduz commented on Makefile
> +watch: export NODE_ENV=development
On purpose, it avoids minification during watch's first stage (`compile-dev`)

2019-06-07 14:21 UTC, menduz commented on packages/config/index.ts
> +        ? 'https://schema-api-v2.now.sh/dar'
https://github.com/decentraland/open-sea-schema-api/issues/6

2019-06-07 14:22 UTC, menduz commented on packages/decentraland-ecs/api-extractor.json
> +/**
I found that very useful while setting it up. I kept it there for future generations, should we remove it?

2019-06-07 14:23 UTC, menduz commented on packages/decentraland-ecs/src/decentraland/Types.ts
> +/** @public */
It marks the annotated declarations to be exported in the .d.ts rollup made by api-extractor. Therefore, every `@public` thing is available in the ECS global context

2019-06-07 14:24 UTC, menduz commented on packages/decentraland-ecs/types/@decentraland/CommunicationsController/index.d.ts
> +declare module '@decentraland/CommunicationsController' {
Nope, it is hand written, it specifies the interface of the modules being loaded by the RPC against the client

2019-06-07 14:24 UTC, menduz commented on packages/decentraland-ecs/types/tsconfig.json
> -      "@decentraland/EntityController",
That file was removed

2019-06-07 14:27 UTC, menduz commented on packages/shared/comms/BrokerConnection.ts
> +      this.ws.onclose = null
In most scenarios yes, we have a TODO to handle reconnections with closes and errors. That may lead us to endless loops. Anyways, we can rearrange it now and change it later. We only have to remember it

2019-06-07 14:29 UTC, menduz commented on packages/shared/comms/BrokerConnection.ts
> +        if (this.stats) {
It changes depending the case
```
this.stats.others.incrementRecv
this.stats.webRtcSession.incrementRecv
```

2019-06-07 14:29 UTC, menduz commented on packages/shared/comms/BrokerConnection.ts
> +      this.logger.log(`signaling state: ${this.webRtcConn!.signalingState}`)
```suggestion
      this.logger.debug(`signaling state: ${this.webRtcConn!.signalingState}`)
```

2019-06-07 14:34 UTC, menduz commented on packages/config/index.ts
> +export const DEBUG_LOCAL_COMMS = location.search.indexOf('LOCAL_COMMS') !== -1 || PREVIEW
done

2019-06-07 14:35 UTC, fmiras approved these changes

2019-06-07 14:35 UTC, fmiras commented on packages/shared/comms/index.ts
> +  let topics = currentParcelTopics + (parcelSceneCommsTopics.length ? ' ' + parcelSceneCommsTopics : '')
could this be `const` instead?

2019-06-07 14:35 UTC, fmiras commented on packages/shared/comms/index.ts
> +  let topics = currentParcelTopics + (parcelSceneCommsTopics.length ? ' ' + parcelSceneCommsTopics : '')
```suggestion
  const topics = currentParcelTopics + (parcelSceneCommsTopics.length ? ' ' + parcelSceneCommsTopics : '')
```

2019-06-07 14:38 UTC, menduz commented on public/test-parcels/-100.100.gamekit-cube/game.ts
> +log('hello a a s')
Believe it or not, we have a test tied to that `log` 💫

2019-06-07 14:41 UTC, menduz commented on packages/decentraland-ecs/types/dcl/index.d.ts
> +
File removed.

2019-06-07 14:42 UTC, menduz commented on packages/decentraland-ecs/types/env/es5.d.ts
>  /// ECMAScript APIs
Nope, it is the file used to provide the environment ECS+ES5 for "import-less" scenes

2019-06-07 14:48 UTC, menduz commented on packages/shared/comms/debug.ts
> +      connection.connection.logDebug()
Addressed

2019-06-07 14:48 UTC, menduz commented on packages/shared/comms/IBrokerConnection.ts
> +  logDebug(): void
`printDebugInformation` it is

2019-06-07 14:49 UTC, menduz commented on packages/shared/comms/BrokerConnection.ts
> +  get hasUnreliable() {
addressed

2019-06-07 14:49 UTC, menduz commented on packages/shared/comms/BrokerConnection.ts
> +  get hasReliable() {
addressed

2019-06-07 14:49 UTC, menduz commented on packages/shared/comms/index.ts
> +  let topics = currentParcelTopics + (parcelSceneCommsTopics.length ? ' ' + parcelSceneCommsTopics : '')
yes

2019-06-07 14:51 UTC, menduz commented on packages/shared/comms/CliBrokerConnection.ts
> +      this.logger.log(state)
there is no .debug in our logger yet :/

2019-06-07 15:03 UTC, eordano commented
Overall:
- The hellmap moves could be their own PR
- The api-extractor update would be great as a different PR

2019-06-07 15:52 UTC, BrianAmadori commented on Makefile
> +	$(MAKE) build-hell-map
If we move this to another PR, maybe we should remove the hell map scenes while we are at it. I found the builder scenes in zone -64,64 are way better for benchmarking.

2019-06-10 12:41 UTC, eordano approved these changes

2019-06-10 12:42 UTC, eordano commented on packages/decentraland-ecs/api-extractor.json
> +/**
It's generated code. No generated code shall be commited. It's noise.

2019-06-10 12:43 UTC, eordano commented on packages/decentraland-ecs/types/env/es5.d.ts
>  /// ECMAScript APIs
Did you write it all? If it's generated code, it should be removed, if it comes from somewhere else we could make it a dependency

2019-06-10 12:44 UTC, eordano commented on packages/shared/comms/BrokerConnection.ts
> +      this.ws.onclose = null
Please add a TODO

2019-06-10 13:02 UTC, merged