feat: use the new & faster content service endpoint
decentraland/kernel-legacy pull request #224
Opened 2019-06-05 06:05 UTC by eordano

Before this change, the data download for a random location in the world is about ~24mb
![image](https://user-images.githubusercontent.com/42750/58933693-86c09180-873e-11e9-89be-dbaecf3e938f.png)

Afterwards, it's 13.6mb
![image](https://user-images.githubusercontent.com/42750/58933242-06e5f780-873d-11e9-8848-43a9a13dddff.png)

This is related to the latest content-service change.

2019-06-05 13:51 UTC, menduz commented on packages/decentraland-loader/lifecycle/controllers/scene.ts
> +        this.downloadManager
use await instead of .then .catch here

2019-06-05 14:54 UTC, eordano commented on packages/decentraland-loader/lifecycle/controllers/scene.ts
> +        this.downloadManager
That's much better, thanks

2019-06-05 20:19 UTC, menduz commented on packages/decentraland-loader/lifecycle/controllers/scene.ts
> +          this.futureOfPositionToCID[position].reject(new Error(`Scene for position ${position} not found`))
```suggestion
          throw new Error(`Scene for position ${position} not found`)
```

2019-06-05 20:20 UTC, menduz commented on packages/decentraland-loader/lifecycle/controllers/scene.ts
> +          return ''
```suggestion

```

2019-06-05 23:55 UTC, eordano commented on packages/decentraland-loader/lifecycle/controllers/scene.ts
> +          return ''
It was really hard to make this decision. It seems to me that failing to fetch a scene is better than a sentinel value, but not very far... (exceptions are for exceptional cases...)

I was thinking that `string|null` might be a better approach. Thoughts?

2019-06-06 14:23 UTC, menduz requested changes
The only thing I see missing is to generate a new "scenes" file in the folder `public/local-ipfs` as long as "mappings"

2019-06-06 14:24 UTC, eordano commented
Yep, that's a blocker

On Thu, Jun 6, 2019 at 11:23 AM Agustin Mendez <notifications@github.com>
wrote:

> *@menduz* requested changes on this pull request.
>
> The only thing I see missing is to generate a new "scenes" file in the
> folder public/local-ipfs as long as "mappings"
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/decentraland/explorer/pull/224?email_source=notifications&email_token=AAAKN7XLWT4GGN5MAHQHWUDPZEMVJA5CNFSM4HTQH7S2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB2ZNTTI#pullrequestreview-246602189>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAAKN7VSVGVKPAVHZNE7QWDPZEMVJANCNFSM4HTQH7SQ>
> .
>

2019-06-06 14:28 UTC, menduz commented on packages/decentraland-loader/lifecycle/controllers/scene.ts
> +          return ''
If you are thinking about a `Maybe<string>` monad, what should we do with the `None` results. Why do we add them to the equation?, because today rejections are clear, it breaks every flow with `await requestSceneCID(...)`. Is there anything useful in returning a null to that await instead of throw?

2019-06-07 10:05 UTC, fmiras submitted a review, later dismissed
I'd like to know why are we using lot's of more futures that promises, If it could be easily get done with promises, I suggest going on that direction is simplier, more standard-ish and let new developers understand the code easier

2019-06-07 10:05 UTC, fmiras commented on packages/decentraland-loader/lifecycle/controllers/download.ts
> +import { future, IFuture } from 'fp-future'
As part of decentraland standars, we import first third party packages and then local packages (this should be at the top)

2019-06-07 10:05 UTC, fmiras commented on packages/decentraland-loader/lifecycle/controllers/download.ts
> +      throw ret
Why are we both rejecting a promises and throwing and error? Shouldn't we doing one of both? is like executing a promise and it will break before even defining the `.catch()`

2019-06-07 10:05 UTC, fmiras commented on packages/decentraland-loader/lifecycle/controllers/download.ts
>          return null
Here's the same, why do we resolve the promise if we're then returning null? I think is useless logic here

2019-06-07 10:05 UTC, fmiras commented on packages/decentraland-loader/lifecycle/controllers/download.ts
> +    log(`Mapping for ${sceneJsonMapping.hash} is ${JSON.stringify(data)}`)
Can we `log.debug` this? The console is already too spammed by other process. I think we should start filtering

2019-06-09 00:42 UTC, eordano commented on packages/decentraland-loader/lifecycle/controllers/scene.ts
> +          return ''
I'd rather have a `Maybe<string>` than a string that is not a valid Scene CID. I would like to be conservative in what this function returns, and there *will* be parcels without content...

2019-06-09 00:43 UTC, eordano commented on packages/decentraland-loader/lifecycle/controllers/download.ts
> +      throw ret
The `reject` is for all other callers to the function, the `throw` (or `return` in other places) is for the caller that triggered the fetch. This is to handle concurrent requests.

2019-06-09 00:44 UTC, eordano commented
> I'd like to know why are we using lot's of more futures that promises, If it could be easily get done with promises, I suggest going on that direction is simplier, more standard-ish and let new developers understand the code easier

I agree with this in principle. It seems to be a pattern that we're using a lot. Maybe it'd be better to just memorize the function -- that will simplify the code a lot. I'll take a swing at it later...

2019-06-10 14:10 UTC, eordano commented
Blocked by https://github.com/decentraland/cli/issues/440

2019-06-10 14:40 UTC, menduz commented
It also requires an implementation in this same repository. Look at the file: https://github.com/decentraland/explorer/blob/master/scripts/createMockJson.ts

2019-06-10 14:41 UTC, menduz submitted a review, later dismissed
It also requires an implementation in this same repository. Look at the file: https://github.com/decentraland/explorer/blob/master/scripts/createMockJson.ts

2019-06-13 00:56 UTC, eordano commented on packages/decentraland-loader/lifecycle/controllers/scene.ts
> +          this.futureOfPositionToCID[position].reject(new Error(`Scene for position ${position} not found`))
No, race condition on multiple requests

2019-06-13 12:24 UTC, eordano commented
Ready to review
Blocked merge on:
- https://github.com/decentraland/content-service/pull/153
- https://github.com/decentraland/cli/pull/442

2019-06-13 12:55 UTC, menduz submitted a review, later dismissed
Does it write a `scenes` file?

2019-06-13 12:55 UTC, menduz commented on packages/decentraland-loader/lifecycle/controllers/download.ts
> +import { error, debug } from 'util'
use our logger, not util

2019-06-13 13:14 UTC, eordano commented
still needs more work

2019-06-14 17:06 UTC, menduz commented on test/testHelpers.ts
> -
❤️

2019-06-14 18:36 UTC, eordano commented
> Does it write a `scenes` file?

yes

> use our logger, not util

done

2019-06-14 18:57 UTC, menduz commented
EXCELLENT VVORK We are good to merge until we release the CLI with `/scenes`, because @next will not work with the current version of the CLI

2019-06-14 18:57 UTC, menduz approved these changes

2019-06-14 21:36 UTC, fmiras approved these changes

2019-06-14 21:37 UTC, merged