fix: start listing parcels near the user
decentraland/kernel-legacy pull request #229
Opened 2019-06-06 11:50 UTC by eordano

This is not a huge improvement -- but it's a starter on prioritizing the download of content that lives closer to the user.

2019-06-06 14:57 UTC, menduz reviewed
Please add a quick comment to the code explaining what those 3 nasty for loops do, ca love letter to our future selves

2019-06-06 20:10 UTC, BrianAmadori requested changes

2019-06-06 20:10 UTC, BrianAmadori commented on packages/decentraland-loader/lifecycle/lib/scope.ts
> +  for (let dx = 1; dx <= config.lineOfSightRadius; dx++) {
We should sort `Vector2` values by squared distance to `position` here and put the results in a temporary list. This code is too illegible.

2019-06-06 20:49 UTC, eordano commented
Thanks for the input! please review this new version.

>

2019-06-06 21:18 UTC, menduz approved these changes
Sabe

2019-06-07 09:53 UTC, fmiras approved these changes

2019-06-07 11:45 UTC, merged