refactor: entrypoints
decentraland/kernel-legacy pull request #245
Opened 2019-06-12 10:25 UTC by fmiras

Contributes #243 

# What? 
- Correctly use `decentraland-auth` iframe (no more popup)
- Only create a WS connection on localhost debugging (moved to another entrypoint + delegated to `test.ts` server of `make watch`)
- Make `index.html` Unity no more `tetra.html`, moved babylon to `babylon.html`
- General refactor

2019-06-12 16:50 UTC, menduz requested changes
If you are goint to take the "class" approach, it will be necessary to encapsulate side effects in constructors like with

https://github.com/decentraland/explorer/pull/245/files#diff-07f990e64d9429c92f9da52d96cf9ac2R10

Otherwise the code is way harder to follow.

2019-06-12 16:50 UTC, menduz commented on packages/unity/DCL.ts
> +export default class DCL {
No need to use a class, use namespaces or file-scoped variables

2019-06-12 16:50 UTC, menduz commented on packages/unity/preview/DCLPreview.ts
> +export default class DCLPreview extends DCL {
Why a class?

2019-06-12 16:50 UTC, menduz commented on scripts/test.ts
> +        res.send(data.replace('dist/index.js', 'dist/debug.js'))
The debug entrypoint must be the same. It only complicate things to test with different files with different side effects

2019-06-12 16:50 UTC, menduz commented on packages/entryPoints/preview.ts
> +const gameInstance = UnityLoader.instantiate('gameContainer', '/unity/Build/unity.json')
Classes and side effects are not compatible

2019-06-13 17:06 UTC, fmiras commented on packages/entryPoints/preview.ts
> +const gameInstance = UnityLoader.instantiate('gameContainer', '/unity/Build/unity.json')
Sorry I don't know what do you mean with side effects here

2019-06-13 17:10 UTC, fmiras commented on scripts/test.ts
> +        res.send(data.replace('dist/index.js', 'dist/debug.js'))
The goal of this is to not have exclusive-development code in production, how else do you think we can achieve this? I was also thinking of using config via env variables during compile times so we don't have TLD-based `if`s

2019-06-13 17:12 UTC, fmiras commented on packages/unity/preview/DCLPreview.ts
> +export default class DCLPreview extends DCL {
I think is better to manage the game instance as an object state rather than a global variable (or actually a whole script-scoped variable) such as `let gameInstance = null` It keeps the entry point code cleaner than before

2019-06-13 17:22 UTC, menduz commented on packages/entryPoints/preview.ts
> +const gameInstance = UnityLoader.instantiate('gameContainer', '/unity/Build/unity.json')
unity initialization is a side effect of loading the script because it is not inside any function, constructor or method

if we are going to take the "encapsulation" approach, then the initialization should be part of a constructor or method

2019-06-13 17:23 UTC, menduz commented on scripts/test.ts
> +        res.send(data.replace('dist/index.js', 'dist/debug.js'))
the thing is we don't test production code, we only test one artifact. in what stage we will notice that the positionReporter is not working in the production dist?

2019-06-13 17:23 UTC, menduz commented on packages/unity/preview/DCLPreview.ts
> +export default class DCLPreview extends DCL {
regarding the side-effect comment, it could be part of UnityPreview class

2019-06-13 18:19 UTC, fmiras commented on scripts/test.ts
> +        res.send(data.replace('dist/index.js', 'dist/debug.js'))
We can still make tests against `index.ts` this `debug.ts` it's mostly for running the explorer within the Unity Editor, I just have to change the tests to keep using index

2019-06-13 19:26 UTC, fmiras commented on packages/unity/DCL.ts
> +export default class DCL {
What's the difference in this case?

2019-06-15 11:57 UTC, eordano commented on packages/entryPoints/preview.ts
> +const gameInstance = UnityLoader.instantiate('gameContainer', '/unity/Build/unity.json')
What Agus is saying here, is that it's not clear that this line injects a `<script>` tag into the `<body>`. Am I right?

2019-06-18 19:21 UTC, fmiras commented
Pending fix and test preview entrypoint

2019-06-20 18:14 UTC, merged