Fix: Implement lossy queued messages
decentraland/kernel-legacy pull request #264
Opened 2019-06-19 14:59 UTC by oOZakMcKrackeNOo

Tag transform and rendering component updates per entity, and remove older elements from the queue if a new update arrives.

#361

2019-06-19 15:02 UTC, BrianAmadori commented on packages/scene-system/scene.system.ts
> +            id: entityId,
If we are sending the `id` like this in all the messages, wouldn't make sense to remove them from the payload to save some json parsing time?

2019-06-19 15:06 UTC, oOZakMcKrackeNOo commented on packages/scene-system/scene.system.ts
> +            id: entityId,
Yes, but I left it for later because there will be another round of optimizations (i.e sending only properties that changes, byte arrays, etc.). If you think we should do it anyway, let's do it!

2019-06-19 15:14 UTC, matiasbargas commented
related to https://github.com/decentraland/unity-client/pull/477

2019-06-19 15:16 UTC, BrianAmadori commented on packages/scene-system/scene.system.ts
> +            id: entityId,
I'm pretty sure there will be some time before we'll be able to make those changes. I think this optimization would be small enough to fit on the same PR :)

2019-06-19 21:44 UTC, eordano commented
Looks great. @menduz any comments?

2019-06-20 01:57 UTC, menduz commented on packages/scene-system/scene.system.ts
> +          id: 'none',
Don't send anything here

2019-06-20 01:58 UTC, menduz commented on packages/scene-system/scene.system.ts
> +            payload: JSON.stringify({} as ComponentDisposedPayload)
```suggestion
            payload: "{}" // JSON.stringify({} as ComponentDisposedPayload)
```

2019-06-20 02:04 UTC, menduz commented
The whole point of {type: string, payload: string}` was to have a high level protocol wrapping/enveloping other packets, this kinda breaks that idea. It makes sense only until we have `id: 'none'`, it is not sound. 

If we find a way to solve the `id: 'none'` and the ambiguity of `id` vs `entityId` `componentId` we may proceed. (AttachEntityComponent)

This PR also breaks babylon implementations of client, preview, tests and editor.

2019-06-20 13:44 UTC, oOZakMcKrackeNOo commented
> The whole point of `{type: string, payload: string}` was to have a high level protocol wrapping/enveloping other packets, this kinda breaks that idea. It makes sense only until we have `id: 'none'`, it is not sound.
> 
> The reason behind that protocol was to have a strategy pattern to parse typed classes depending on the `.type` field of the packet.
> 
> If we find a way to solve the `id: 'none'` and the ambiguity of `id` vs `entityId` `componentId` we may proceed. (AttachEntityComponent). If we cannot find a good solution for the model of the high-level wrapper, we can take the information out of the `.payload` right before sending it to unity. But at the cost of more CPU usage
> 
> This PR also breaks babylon implementations of client, preview, tests and editor.

I understand why it was implemented this way, but we need to know the component id before parsing the whole payload in order to identify old messages and remove them when a new one has arrived. Let's discuss a better way to achieve this without breaking compatibility with babylon implementation.

2019-06-20 14:10 UTC, menduz commented
You can keep the PR as it as it is if you apply the changes to fix babylon and remove the `id: 'none'` by making the id optional

So the envelope may now have the following type

```ts
type EnvelopeMessage = {
  type: string // type of message being carried
  id?: number // id of the object (entity or component) related to the message (optional)
  payload: string // json string of the packet defined by the field .type
}
```

And we need stronger definitions about the package `AttachEntityComponent` about what does `id` mean there. is it entityId or componentId?

2019-06-20 21:35 UTC, eordano commented
Won't merge unless the tests pass

2019-06-22 00:38 UTC, eordano commented
May I suggest calling this `tag` instead of `id`? In general, I agree with Agus' comments in that there seems to be a mixture of abstraction layers.

Although, (and that's why `tag` becomes more relevant) frequently there are leaks of information between protocols that grow together. I think that the high cost of marshalling/unmarshalling makes this change a must have

2019-06-23 08:53 UTC, fmiras commented on packages/scene-system/scene.system.ts
> +            id: entityId,
YAGNI -> https://martinfowler.com/bliki/Yagni.html

2019-06-23 08:56 UTC, fmiras submitted a review, later dismissed

2019-06-23 08:56 UTC, fmiras commented on packages/scene-system/scene.system.ts
> +              id: id,
You can just use `id`, is called object property short-hand, info: https://alligator.io/js/object-property-shorthand-es6
```suggestion
              id,
```

2019-06-23 08:56 UTC, fmiras commented on packages/scene-system/scene.system.ts
> +              id: id,
```suggestion
              id,
```

2019-06-23 08:56 UTC, fmiras commented on packages/scene-system/scene.system.ts
> +            id: id,
```suggestion
            id,
```

2019-06-23 08:56 UTC, fmiras commented on packages/scene-system/scene.system.ts
> +            id: id,
```suggestion
            id,
```

2019-06-23 22:25 UTC, eordano approved these changes

2019-06-23 22:35 UTC, menduz commented on packages/unity-interface/dcl.ts
> +    gameInstance.SendMessage(`SceneController`, `SendSceneMessage`, `${parcelSceneId}\t${tag}\t${method}\t${payload}`)
It is better to add things to the tail of the packets when changing protocols? If we do, it may work before updating the unity build

2019-06-23 22:36 UTC, eordano commented on packages/unity-interface/dcl.ts
> +    gameInstance.SendMessage(`SceneController`, `SendSceneMessage`, `${parcelSceneId}\t${tag}\t${method}\t${payload}`)
that's right! thank you

2019-06-24 14:26 UTC, fmiras requested changes

2019-06-24 14:26 UTC, fmiras commented on packages/shared/types.ts
> +  tag?: string
In which cases is this tag `undefined` or missing?

2019-06-24 14:26 UTC, fmiras commented on packages/unity-interface/dcl.ts
> +  sendSceneMessage(parcelSceneId: string, method: string, payload: string, tag?: string) {
In this case I think that `tag` should be optional
```suggestion
  sendSceneMessage(parcelSceneId: string, method: string, payload: string, tag: string) {
```

2019-06-24 14:31 UTC, menduz commented on packages/shared/types.ts
> +  tag?: string
It was when using 'none' but it now uses 'scene' and it makes more sense

2019-06-24 14:48 UTC, eordano commented on packages/unity-interface/dcl.ts
> +  sendSceneMessage(parcelSceneId: string, method: string, payload: string, tag?: string) {
isn't it?

2019-06-24 14:48 UTC, eordano commented on packages/shared/types.ts
> +  tag?: string
Tag is optional

2019-06-24 14:48 UTC, eordano commented on packages/shared/types.ts
> +  tag?: string
There may be messages without any tag

2019-06-24 15:07 UTC, menduz commented on packages/unity-interface/dcl.ts
> +  sendSceneMessage(parcelSceneId: string, method: string, payload: string, tag?: string) {
should NOT be optional perhaps?

2019-06-25 02:13 UTC, eordano commented
I think optional is fine

On Mon, 24 Jun 2019 at 12:07 Agustin Mendez <notifications@github.com>
wrote:

> *@menduz* commented on this pull request.
> ------------------------------
>
> In packages/unity-interface/dcl.ts
> <https://github.com/decentraland/explorer/pull/264#discussion_r296771366>:
>
> > @@ -111,12 +111,12 @@ const unityInterface = {
>      }
>      gameInstance.SendMessage('SceneController', 'LoadParcelScenes', JSON.stringify(parcelsToLoad[0]))
>    },
> -  sendSceneMessage(parcelSceneId: string, method: string, payload: string) {
> +  sendSceneMessage(parcelSceneId: string, method: string, payload: string, tag?: string) {
>
> should NOT be optional perhaps?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/decentraland/explorer/pull/264?email_source=notifications&email_token=AAAKN7RD5VRBZTAZBDUEB5LP4DPJ5A5CNFSM4HZKRMPKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB4N3URY#discussion_r296771366>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAAKN7UGOWB74VTQTYHLN53P4DPJ5ANCNFSM4HZKRMPA>
> .
>

2019-06-25 02:20 UTC, menduz commented
If you send optional in `sendSceneMessage(a,b,c,tag?: string)` the sent string will end with a `\tundefined`

2019-06-26 02:51 UTC, fmiras requested changes

2019-06-26 02:51 UTC, fmiras commented on public/test-parcels/0.0.genetic-experiment/Button.ts
> +  /* update(dt: number) {
Please no commented code, If it's for something a TODO task at most with a commit hash reference

2019-06-26 02:51 UTC, fmiras commented on public/test-parcels/0.0.genetic-experiment/Environment.ts
> +  constructor(temp: number, pos: Vector3, size: number) {
tip: by just using `constructor(private temperature: number)` you don't need to do `this.temperature = temp` also, characters are free, no need of use just "temp" it could be confusing

Same with pos and size

2019-06-26 02:51 UTC, fmiras commented on packages/unity-interface/dcl.ts
> +  sendSceneMessage(parcelSceneId: string, method: string, payload: string, tag?: string) {
Sorry I meant NOT optional

2019-06-26 02:51 UTC, fmiras commented on public/test-parcels/0.0.genetic-experiment/Environment.ts
> +    let newCreaturesCount = this.creatures.push(newCreature)
use always `const` when defining a varable that is not going to be re-assigned

2019-06-26 02:51 UTC, fmiras commented on public/test-parcels/0.0.genetic-experiment/Environment.ts
> +    let newCreaturesCount = this.creatures.push(newCreature)
```suggestion
    const newCreaturesCount = this.creatures.push(newCreature)
```

2019-06-26 07:17 UTC, eordano commented on packages/unity-interface/dcl.ts
> +  sendSceneMessage(parcelSceneId: string, method: string, payload: string, tag?: string) {
No

2019-06-26 17:54 UTC, menduz commented on public/test-parcels/0.0.genetic-experiment/Button.ts
> +  /* update(dt: number) {
It is a test scene

2019-06-26 17:55 UTC, menduz commented on public/test-parcels/0.0.genetic-experiment/Environment.ts
> +  constructor(temp: number, pos: Vector3, size: number) {
It is a test scene

2019-06-28 14:16 UTC, menduz requested changes

2019-06-28 14:16 UTC, menduz commented on packages/scene-system/scene.system.ts
> +              tag: entityId + '_' + classId,
Ok, this protocol changes don't make sense anymore. 

We should better think about what we want to do and then execute cleanly.

2019-07-01 15:55 UTC, oOZakMcKrackeNOo commented on packages/scene-system/scene.system.ts
> +              tag: entityId + '_' + classId,
It's a compromise solution with what we've got at the moment. Right now the Transform entity component is the only lossy message. Next we'll add other components and we have to design a way to manually tell which messages are lossy and which aren't. So maybe the refactor you ask for could be made in that ticket. What do you think?

2019-07-01 17:10 UTC, menduz commented on packages/scene-system/scene.system.ts
> +              tag: entityId + '_' + classId,
I think we should take a more formal process for this issue since the changes went out of our hands. Formalize the requirements in one issue or one pager and discuss it before writing any line of code. AFAIK this problem can also be solved by using protocol buffers and it requires a more radical but better defined change, so this PR will become useless.

2019-07-01 20:14 UTC, oOZakMcKrackeNOo commented on packages/scene-system/scene.system.ts
> +              tag: entityId + '_' + classId,
What we need is to access some of the data while preventing parsing the whole payload just to get them. And that data may vary between messages (for example classId). What do you suggest? Now we're using the tag like a parameters list.

2019-07-01 20:20 UTC, menduz commented on packages/scene-system/scene.system.ts
> +              tag: entityId + '_' + classId,
I suggest to write down the reasons to make this change and then based on those reasons plan and execute with a better idea, this is start from a solution, a hack.

2019-07-03 00:17 UTC, eordano commented on public/test-parcels/0.0.genetic-experiment/Environment.ts
> +  constructor(temp: number, pos: Vector3, size: number) {
why do we lower the bar for test scenes?

2019-07-03 13:51 UTC, menduz approved these changes

2019-07-03 15:22 UTC, merged