feat: builder unity integration
decentraland/kernel-legacy pull request #274
Opened 2019-06-21 21:10 UTC by belohlavek

# What? 
...

# Why? 
...

2019-08-28 12:51 UTC, eordano commented
Hey @belohlavek is this still active?

2019-08-30 19:17 UTC, belohlavek commented
Super active

2019-08-30 19:47 UTC, moliva commented
Thanks for the clarification. :D

2019-10-16 17:19 UTC, moliva requested changes

2019-10-16 17:19 UTC, moliva commented on packages/config/index.ts
> +export const ENABLE_WEB3 = location.search.indexOf('ENABLE_WEB3') !== -1 || !!(global as any).enableWeb3 || !EDITOR
This will enable web 3 when not in editor mode even if the `ENABLE_WEB3` is not present.
```suggestion
export const ENABLE_WEB3 = location.search.indexOf('ENABLE_WEB3') !== -1 || !!(global as any).enableWeb3
```

2019-10-16 17:19 UTC, moliva commented on packages/entryPoints/editor.ts
> +  })
Mind that if the scene reported is not the same as the one expected this observable won't be called again (because of the `addOnce`), this could be due to the UI scene or any other generated one being loaded. Not sure if we are using any of them still in the builder.
Another version could be:
```suggestion
  const observer = sceneLifeCycleObservable.add(obj => {
    if (sceneData.sceneId === obj.sceneId && obj.status === 'ready') {
      sceneLifeCycleObservable.remove(observer)
      engineReady.resolve(true)
    }
  })
```

2019-10-16 17:19 UTC, moliva commented on packages/entryPoints/editor.ts
> +    readyBuilderScene()
Maybe it would be better to export the `unityInterface` and call their methods from here.

2019-10-16 17:19 UTC, moliva commented on packages/entryPoints/editor.ts
> +  ActivateRendering()
Same as above.

2019-10-16 17:19 UTC, moliva commented on packages/unity-interface/dcl.ts
> +export function selectGizmoBuilder(type: string) {
Let's inline these methods and add them to unity interface and remove the generic `sendBuilderMessage`.

2019-10-16 17:19 UTC, moliva commented on packages/unity-interface/dcl.ts
> +  defaultLogger.info('mappings: ', sceneData.mappingsResponse)
```suggestion
```

2019-10-16 17:19 UTC, moliva commented
Let's drop the package-lock and unityweb files as well.

2019-10-16 17:55 UTC, moliva commented on packages/entryPoints/editor.ts
> +  console.log('K', scene._mappings)
```suggestion
```

2019-10-16 17:57 UTC, moliva commented on packages/unity-interface/dcl.ts
> +  defaultLogger.info('Updating Builder Scene...')
```suggestion
```

2019-10-16 17:59 UTC, moliva commented on packages/unity-interface/dcl.ts
> +  SendBuilderMessage(method: string, payload: string = '') {
```suggestion
  // @internal  
  SendBuilderMessage(method: string, payload: string = '') {
```

2019-10-16 18:43 UTC, moliva approved these changes

2019-10-16 19:13 UTC, merged