ensure correct artifact building
decentraland/kernel-legacy pull request #277
Opened 2019-06-22 15:25 UTC by matiasbargas

2019-06-23 08:48 UTC, fmiras requested changes

2019-06-23 08:48 UTC, fmiras commented on scripts/prepareDist.ts
> +      console.log(`>   replacing ${original} -> ${newFileName}`)
```suggestion
      console.log(`> replacing ${original} -> ${newFileName}`)
```

2019-06-23 08:48 UTC, fmiras commented on scripts/prepareDist.ts
> +  console.log(`> replace ${fileNameToReplace}.js -> ${newFileName} in html`)
Please be consistent using present continuous verbs or infinitive, but not the two of them

2019-06-23 08:48 UTC, fmiras commented on scripts/prepareDist.ts
> +    content = content.replace(new RegExp(fileNameToReplace + '.(S+.)?js'), function(original) {
Use arrow function here

2019-06-23 08:48 UTC, fmiras commented on scripts/prepareDist.ts
> +    content = content.replace(new RegExp(fileNameToReplace + '.(S+.)?js'), function(original) {
I think we should use regex literals to be consistent with the rest of the code

2019-06-23 08:48 UTC, fmiras commented on scripts/prepareDist.ts
> +    let didReplace = false
Just compare the already existing variables, you can use `content` for "original" and `result` for the regex match, and if they are the same you already know if it was replaced or not

2019-06-23 18:51 UTC, eordano commented on scripts/prepareDist.ts
> +    content = content.replace(new RegExp(fileNameToReplace + '.(S+.)?js'), function(original) {
I wasn't aware that regexp literals was possible with template `` strings, is it?

2019-06-24 14:31 UTC, fmiras commented on scripts/prepareDist.ts
> +    content = content.replace(new RegExp(fileNameToReplace + '.(S+.)?js'), function(original) {
Just looked into it, you can't so my bad!

2019-08-06 21:21 UTC, closed without merging