fix: scene messages
decentraland/kernel-legacy pull request #288
Opened 2019-06-24 22:39 UTC by menduz

Scene messages must reach every scene including the UI, not only parcel scenes in the map

https://giphy.com/embed/WOYKaXG2xJsBO

2019-06-24 23:23 UTC, eordano approved these changes

2019-06-25 16:10 UTC, fmiras commented on packages/engine/dcl/index.ts
> +            loadedParcelSceneWorkers.forEach($ =>
I like `loadedSceneWorkers` better :(

2019-06-25 18:53 UTC, fmiras commented on packages/decentraland-loader/lifecycle/controllers/download.ts
> +  scene_cid: ''
for what is this for?

2019-06-25 18:57 UTC, fmiras commented on packages/decentraland-loader/lifecycle/controllers/download.ts
> +    // stub
What's this?

2019-06-25 18:59 UTC, menduz commented on packages/decentraland-loader/lifecycle/controllers/download.ts
> +    // stub
a stub comment. an empty function that needs to exist (constructor) because of our linter doesn't like empty functions

2019-06-25 19:00 UTC, menduz commented on packages/decentraland-loader/lifecycle/controllers/download.ts
> +  scene_cid: ''
a typing of the server's response. it always returns an empty string

2019-06-25 19:05 UTC, fmiras requested changes

2019-06-25 19:05 UTC, fmiras commented on packages/decentraland-loader/lifecycle/controllers/download.ts
> +      return this.positionToSceneId.get(pos)!
Why the null assertion here? We're already returning a `Promise<string | null>` the user of this function will have to still validate if not null or not

2019-06-25 19:05 UTC, fmiras commented on packages/entryPoints/editor.ts
> +    return new Set(loadedSceneWorkers.values())
Cool

2019-06-25 19:19 UTC, menduz commented on packages/decentraland-loader/lifecycle/controllers/download.ts
> +      return this.positionToSceneId.get(pos)!
because it can be resolved to either string | null or throw. null is a valid value

2019-06-25 19:29 UTC, merged

2019-06-25 21:37 UTC, eordano commented on packages/entryPoints/editor.ts
> +    return new Set(loadedSceneWorkers.values())
That defensive programming