feat: profile integration
decentraland/kernel-legacy pull request #346
Opened 2019-07-19 20:09 UTC by moliva

# What? 
Closes #194.

Integrates `explorer` with Profile service and builds the corresponding avatar shape for each profile.

# Why? 
Bring the avatars created in the Avatar creation app to the world.

2019-07-19 20:14 UTC, menduz commented on packages/shared/types.ts
> +type Color4 = {
missing `export`

2019-07-19 20:15 UTC, menduz commented on packages/shared/world/profiles.ts
> +  shape.baseUrl = `${getServerConfigurations().avatar.contents}/`
what do you think about adding the tailing `/` to the config directly?

2019-07-19 20:19 UTC, menduz requested changes

2019-07-19 20:19 UTC, menduz commented on packages/ui/avatar/avatarSystem.ts
> +  avatar = createAvatar(profile)
!!!!!

`ensureAvatar` may get called several times and trigger several `await resolveProfile(uuid)` since it has to wait for the previous `await resolveProfile(uuid)` for completion

is it possible to create the avatar and then load the profile as a method?

so the code will look like
```ts
avatar = new AvatarEntity(uuid)
avatarMap.set(uuid, avatar)
avatar.resolveProfile()
```

2019-07-19 20:19 UTC, menduz commented on packages/ui/avatar/avatarSystem.ts
> +async function handleUserData(message: ReceiveUserDataMessage): Promise<void> {
this should be a synchronous function

2019-07-19 20:19 UTC, menduz commented on packages/ui/avatar/avatarSystem.ts
> +async function handleUserPose({ uuid, pose }: ReceiveUserPoseMessage): Promise<boolean> {
this should be a synchronous function

2019-07-19 20:19 UTC, menduz commented on packages/ui/avatar/avatarSystem.ts
> +async function handleUserVisible({ uuid, visible }: ReceiveUserVisibleMessage): Promise<void> {
this should be a synchronous function

2019-07-29 20:07 UTC, leohgc approved these changes

2019-07-29 20:19 UTC, merged