fix: sending new position to prior position topic when transitioning
decentraland/kernel-legacy pull request #580
Opened 2019-10-15 22:14 UTC by moliva

Fixes #576 .

2019-10-17 22:55 UTC, eordano commented on packages/shared/comms/index.ts
> +const UNREACHABLE_POSITION = [1000, 1000, 1000, 0, 0, 0, 0] as Position
Warning! This falls in parcel `62,62`

2019-10-17 22:55 UTC, eordano requested changes
`62,62` is not unreachable

2019-10-18 04:38 UTC, moliva commented on packages/shared/comms/index.ts
> +const UNREACHABLE_POSITION = [1000, 1000, 1000, 0, 0, 0, 0] as Position
Good catch!

2019-10-20 11:59 UTC, eordano approved these changes

2019-10-20 12:02 UTC, eordano approved these changes
Nit

2019-10-20 12:02 UTC, eordano commented on packages/shared/comms/index.ts
> +  parcelLimits.parcelSize * 1000,
```suggestion
  1000 * parcelLimits.parcelSize,
```
Yoda notation might help here?

2019-10-20 23:46 UTC, merged