chore: normalize ecs apis
decentraland/kernel-legacy pull request #60
Opened 2019-03-14 18:21 UTC by menduz

2019-03-20 18:19 UTC, fmiras commented on packages/build-ecs/index.ts
> +      if (compiled.error) {
Could we use `else if (compiled.error) {` here?

2019-04-23 22:57 UTC, menduz commented on packages/build-ecs/index.ts
> +      if (compiled.error) {
yes

2019-04-23 22:57 UTC, menduz commented on packages/decentraland-ecs/src/decentraland/Components.ts
> +    uuidEventSystem.handlerMap[this.uuid] = this
@pravusjif please move the line

```ts
uuidEventSystem.handlerMap[this.uuid] = this
```
back into the constructor of `OnChanged` and `OnTextSubmit`.

a comment can be added like
```ts
// this injection is necessary ONLY in events that are ALWAYS turned on and are
// not assignable to entities. Like events for the UI elements
uuidEventSystem.handlerMap[this.uuid] = this
```

2019-04-23 22:57 UTC, menduz commented on packages/decentraland-ecs/src/decentraland/UIShapes.ts
> +  name: string | null = null
Why do we need a 'name' field? is this used somewhere?

2019-04-29 17:41 UTC, pravusjif commented on packages/decentraland-ecs/src/decentraland/UIShapes.ts
> +  name: string | null = null
We use the 'name' field (previously called 'id' and didn't provide any real use for the dev on typescript) mostly for debugging, so that by configuring a name to the components/entities, once instantiated in unity we can finde them quickly

2019-04-29 17:50 UTC, fmiras submitted a review, later dismissed

2019-04-29 17:50 UTC, fmiras commented on packages/ui/avatar/avatarSystem.ts
> +  //OnPointerDown
Why is this a comment?

2019-04-29 17:50 UTC, fmiras commented on packages/ui/avatar/avatarSystem.ts
> +//import { showAvatarWindow, currentAvatarId, hideAvatarWindow } from './avatarWindow'
Another one here

2019-04-29 17:50 UTC, fmiras commented on packages/ui/avatar/avatarSystem.ts
> +      let labelTransform = this.labelEntity.getComponentOrCreate(Transform)
Could this be `const` instead?

2019-04-29 17:50 UTC, fmiras commented on public/ecs-parcels/-200,110-relative-layout-ui/game.ts
>  // inventoryContainer.adaptHeight = true --- you can only set adaptWidth (X)OR adaptHeight for it to work correctly
Could we either delete this or put a TODO task with an issue attached?

2019-04-29 17:50 UTC, fmiras commented on public/ecs-parcels/-200,110-relative-layout-ui/game.ts
> +// inventoryContainer.color = 'white' // previously set child text color
Same here

2019-04-29 17:50 UTC, fmiras commented on packages/dcl/widgets/ui.ts
> +    // tslint:disable-next-line:no-unused-expression
I think we should either respect this rule or remove it, there is no point of putting it and avoid it with comments

2019-04-29 17:50 UTC, fmiras commented on packages/shared/world/parcelSceneManager.ts
> +  for (let parcelSceneWorker of loadedParcelSceneWorkers) {
We're using in some cases traditional `for` indexed-syntax and in other cases this syntax, I'd to be consistent with this, here we should use either es5 `for` statement or `Array.prototype.find` function

2019-04-29 18:48 UTC, matiasbargas requested changes

2019-04-29 18:48 UTC, matiasbargas commented on packages/decentraland-ecs/src/decentraland/Components.ts
> +import { uuidEventSystem } from './Systems';
This import is causing a circular dependency because `System` is adding `Components` as import as well. I Recommend to move OnUUIDEvent to a new file to solve this.

2019-04-29 18:48 UTC, BrianAmadori commented on public/ecs-parcels/-200,110-relative-layout-ui/game.ts
>  // inventoryContainer.adaptHeight = true --- you can only set adaptWidth (X)OR adaptHeight for it to work correctly
Those comments are outdated, I removed all of them. We must create a task to fix this scene as its written for the old SDK though.

2019-04-29 18:49 UTC, BrianAmadori commented on public/ecs-parcels/-200,110-relative-layout-ui/game.ts
> +// inventoryContainer.color = 'white' // previously set child text color
Those comments are outdated, I removed all of them. We must create a task to fix this scene as its written for the old SDK though.

2019-04-29 19:14 UTC, BrianAmadori commented on packages/shared/world/parcelSceneManager.ts
> +  for (let parcelSceneWorker of loadedParcelSceneWorkers) {
The traditional `for` indexed is o.k. for arrays, here we are dealing with a `Set`. Iteration-wise they are pears and oranges. The `of` approach is the most readable one with this data structure AFAIK.

2019-04-29 19:20 UTC, BrianAmadori commented on packages/dcl/widgets/ui.ts
> +    // tslint:disable-next-line:no-unused-expression
I believe this is a intended special case because the `new SceneWorker()` triggers its initialization and registers it to `ParcelScene`. You don't want to save it to a reference, just get it working.

2019-04-29 19:23 UTC, menduz commented on packages/shared/world/parcelSceneManager.ts
> +  for (let parcelSceneWorker of loadedParcelSceneWorkers) {
It is ok. It doesn't have a .find function

2019-04-29 19:25 UTC, menduz commented on packages/dcl/widgets/ui.ts
> +    // tslint:disable-next-line:no-unused-expression
It is normally an error to have expressions in that way. Except for this case, where it is necessary. I believe it is ok to leave the comment and the rule

2019-04-29 19:40 UTC, menduz commented
@BrianAmadori hay que hacer un `export * from ...` en `decentraland-ecs/src/index.ts`

porque 

```ts
import { OnClick } from 'decentraland-ecs/src'
```
tiene que funcionar OOTB

2019-04-29 22:30 UTC, matiasbargas approved these changes

2019-05-03 17:51 UTC, merged