chore: json split for LoadParcelScenes message
decentraland/kernel-legacy pull request #75
Opened 2019-03-20 15:49 UTC by BrianAmadori

# What? 
This splits the LoadParcelScenes json with `<break>` statements. 

# Why? 
This allows throttling the JSON parsing from game engine side, as its too big now and causes performance hiccups.

2019-03-20 18:17 UTC, fmiras requested changes
We're still sending just one message, have you got one example of the JSON that you want to parse? maybe you can split it without a "<break>" delimiter (wtf, i can edit your comment?)

2019-03-20 18:17 UTC, fmiras commented on packages/unity-interface/dcl.ts
> +      var finalJson: string = "";
It is not recommended to use `var` statements anymore since ES6, use `let` variables that are going to be redefined and `const` for variables that are not going to be redefined

2019-03-20 18:17 UTC, fmiras commented on packages/unity-interface/dcl.ts
> +        var parcel = parcelsToLoad[i]
You can also use `const` here

2019-03-20 18:17 UTC, fmiras commented on packages/unity-interface/dcl.ts
> +        if (i < parcelsToLoad.length - 1)
Always use curly braces " { } " for defining blocks. It helps code readability + avoid skipping code execution

2019-03-20 21:04 UTC, BrianAmadori commented
> We're still sending just one message, have you got one example of the JSON that you want to parse? maybe you can split it without a "" delimiter (wtf, i can edit your comment?)

It should look like

```
{
   { stuff },
   { stuff }
}<break>
{
   { stuff },
   { stuff }
}<break>
{
   { stuff },
   { stuff }
}
```

I have to admit that I kind of hate the approach. I couldn't split it in several messages because the client expect the message to be processed instantly and this doesn't work well in WSS mode. I used the `<break>` as delimiter because I don't feel comfy with a single character. Maybe its better to just use `chr(13)` or similar.

2019-03-21 17:33 UTC, fmiras commented
> > We're still sending just one message, have you got one example of the JSON that you want to parse? maybe you can split it without a "" delimiter (wtf, i can edit your comment?)
> 
> It should look like
> 
> ```
> {
>    { stuff },
>    { stuff }
> }<break>
> {
>    { stuff },
>    { stuff }
> }<break>
> {
>    { stuff },
>    { stuff }
> }
> ```
> I have to admit that I kind of hate the approach. I couldn't split it in several messages because the client expect the message to be processed instantly and this doesn't work well in WSS mode. I used the `<break>` as delimiter because I don't feel comfy with a single character. Maybe its better to just use `chr(13)` or similar.

What if we use the expression `}\n{` or `}{`? That's not valid JSON so we can detect the different messages like that and save 7 extra bytes string per message (<break>)

2019-03-22 15:17 UTC, BrianAmadori commented
> > > We're still sending just one message, have you got one example of the JSON that you want to parse? maybe you can split it without a "" delimiter (wtf, i can edit your comment?)
> > 
> > 
> > It should look like
> > ```
> > {
> >    { stuff },
> >    { stuff }
> > }<break>
> > {
> >    { stuff },
> >    { stuff }
> > }<break>
> > {
> >    { stuff },
> >    { stuff }
> > }
> > ```
> > I have to admit that I kind of hate the approach. I couldn't split it in several messages because the client expect the message to be processed instantly and this doesn't work well in WSS mode. I used the `<break>` as delimiter because I don't feel comfy with a single character. Maybe its better to just use `chr(13)` or similar.
> 
> What if we use the expression `}\n{` or `}{`? That's not valid JSON so we can detect the different messages like that and save 7 extra bytes string per message ()

Not bad, only thing is JSON is gonna look like a bit funky:
```
{
   { stuff },
   { stuff }
}}{
{
   { stuff },
   { stuff }
}
```
But the split would work.

2019-03-22 15:37 UTC, fmiras approved these changes

2019-03-28 17:30 UTC, merged